---
- name: Create user for steam server and add ssh key
  hosts: all
  gather_facts: false
  vars_files: vars.yml
  remote_user: root
  roles:
    - createusr

- name: Create Valheim Server
  hosts: all
  gather_facts: true
  vars_files: vars.yml
  remote_user: '{{ valheim_usr }}'
  roles:
    - valheimserver
