---
- name: Create the Steam directory for SteamCMD
  ansible.builtin.file:
    path: "~/Steam"
    state: directory

- name: Create tmp directory 
  ansible.builtin.file:
    path: "/tmp/steamcmdinstall"
    state: directory

- name: Download steamCMD
  get_url:
    url: "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
    dest: '/tmp/steamcmdinstall/'

- name: Extract steamcmd_linux.tar.gz into ~/Steam
  ansible.builtin.unarchive:
    remote_src: yes
    src: '/tmp/steamcmdinstall/steamcmd_linux.tar.gz'
    dest: '~/Steam'

- name: Execute sudo stuff
  block:
    - name: Install lib32gcc-s1
      ansible.builtin.apt:
        update_cache: yes
        name: lib32gcc-s1
        state: latest

  become: true
  become_user: root

- name: Delete tmp directory 
  ansible.builtin.file:
    path: "/tmp/steamcmdinstall"
    state: absent

- name: Create Valheim Save directory 
  ansible.builtin.file:
    path: "{{ valheim_server_savedir }}"
    state: directory

#- name: Create Valheim log directory 
#  ansible.builtin.file:
#    path: "{{ valheim_server_savedir }}/logs"
#    state: directory

- name: Install Valheim dedicated Server
  ansible.builtin.command: 
    cmd: "bash ~/Steam/steamcmd.sh +@sSteamCmdForcePlatformType linux +force_install_dir ~/Valheimserver +login anonymous +app_update 896660 validate +quit"

- name: Create Valheim config  
  ansible.builtin.template:
    src: templates/start_server.sh.j2
    dest: ~/Valheimserver/start_server.sh
  
- name: make Valheim server executable
  ansible.builtin.command: 
    cmd: "chmod +x ~/Valheimserver/start_server.sh"

- name: Execute sudo stuff
  block:

  - name: Create Valheimserver service
    ansible.builtin.template:
      src: templates/valheimserver.service.j2
      dest: /etc/systemd/system/valheimserver.service

  - name: Reload deamons
    ansible.builtin.command: 
      cmd: "systemctl daemon-reload"

  - name: Enable Valheim server to run on system start
    ansible.builtin.command:
      cmd: "systemctl enable valheimserver.service"

  - name: Start Valheim server
    ansible.builtin.command:
      cmd: "systemctl start valheimserver.service"

  - name: Get Valheim server Service status
    ansible.builtin.command:
      cmd: "systemctl status valheimserver.service"
    register: Server_Status
    
  - name: Print server status
    debug:
      var: Server_Status

  become: true
  become_user: root